package edu.tus.guitarstore.entity;

import java.util.List;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Brand extends BaseEntity {

    /**
     * The unique identifier for the Brand entity.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * The name of the brand.
     * This field must be unique.
     */
    @Column(name = "name", unique = true)
    private String name;

    /**
     * The country where the brand is based.
     */
    private String country;

    /**
     * The list of guitars associated with this brand.
     * This establishes a one-to-many relationship with the Guitar entity.
     */
    @OneToMany(mappedBy = "brand", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude // prevent infinite loops with Lombok
    private List<Guitar> guitars;
}
