package edu.tus.guitarstore.entity;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Guitar extends BaseEntity {

    /**
     * The unique identifier for the Guitar entity.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * The model name of the guitar. This field is mandatory
     * and must be unique across all Guitar records.
     * must match database schema, and be unique
     */
    @Column(name = "model_name", unique = true)
    private String modelName;

    /**
     * The price of the guitar. This field is mandatory.
     */
    @Column(name = "price")
    private double price;

    /**
     * The manufacture date of the guitar. This field is mandatory.
     */
    @Column(name = "manufacture_date", columnDefinition = "DATE")
    private LocalDate manufactureDate;

    /**
     * The brand associated with the guitar.
     * This establishes a many-to-one relationship with the Brand entity.
     * Match FK column schema.sql
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brand_id")
    private Brand brand;
}
