site_name: Guitar Store API Docs
docs_dir: docs
site_dir: site
theme:
  logo: images/logo.png
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  name: material
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top

nav:
  - Home: 
    - index.md
  - Microservices Architecture:
    - microservices-architecture-ca1/index.md
  - Continuous Build and Delivery:
    - continuous-build-and-delivery-ca1/index.md
  - Guide:
    - guide/index.md
    - guide/2_project_overview.md
    - guide/3_core_tech.md
    - guide/4_tech_stack.md
    - guide/5_api_demo.md
    - guide/6_diagrams.md
    - guide/7_database.md
    - guide/8_status_codes.md
    - guide/9_end_points.md
  - Testing:
    - Overview: testing/index.md
    - Demo: testing/demo.md
    - Unit Tests:
      - Overview: testing/unit-tests/index.md
    - Integration Tests:
      - Overview: testing/integration-tests/index.md
      - GuitarRepositoryIntegrationTest: testing/integration-tests/guitar-repository-integration-test.md
      - GuitarRepositoryTest: testing/integration-tests/guitar-repository-test.md
    - End-to-End Tests:
      - Overview: testing/end-to-end-tests/index.md
      - API (TestRestTemplate): testing/end-to-end-tests/api-end-to-end.md
      - Karate: testing/end-to-end-tests/karate.md
  - Links:
    - links/index.md
  
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.superfences
  
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - index.md

repo_url: https://github.com/joeaoregan/TUS-26-MA-CA1-Guitar-Store-API
repo_name: GitHub

site_url: https://joeaoregan.github.io/TUS-26-MA-CA1-Guitar-Store-API/