# sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.projectKey=java-sonar-scanner-cbd-1
sonar.projectName=Guitar Store API
sonar.projectVersion=1.0
sonar.scm.disabled=true
sonar.sources=src/main/java
sonar.language=java # Optional if SonarQube can automatically detect the language

sonar.java.binaries=target/classes
sonar.java.testBinaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
# sonar.java.libraries=M2_REPOSITORY/**/*.jar
# sonar.java.test.libraries=M2_REPOSITORY/**/*.jar