# key principle of the twelve-factor app methodology - declarative (declare port number)
server:
  port: ${PORT:8080}

# Use placeholders to read from environment variables or .env file
spring:
  application:
    version: 1.0.0
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:guitardb}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
# run scripts every time app starts:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
# Explicitly define H2 console path
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
#     database-platform: org.hibernate.dialect.H2Dialect # db agnostic
# first create table then insert data:
    hibernate:
#      ddl-auto: validate # use once schema finalised
      ddl-auto: update # able to alter tables
    show-sql: true
# print sql queries in a readable format
    properties:
      hibernate:
        format_sql: true
# Custom metadata
app:
  title: Guitar Store Management API
  version: 1.0.0
  author: Joe O'Regan
  email: A00258304@student.tus.ie
  github: https://github.com/joeaoregan/TUS-26-MA-CA1-Guitar-Store-API
  description:
    A comprehensive RESTful API for managing musical instrument inventory. 
    Developed as part of the Microservices Architecture Module. 
    Key features include N-tier architecture, JPA Auditing, and DTO-based separation.