# key principle of the twelve-factor app methodology - declarative (declare port number)
server:
  port: ${PORT:8080}

# Use placeholders to read from environment variables or .env file
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:guitardb}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
# run scripts every time app starts:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
# Explicitly define H2 console path
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
#     database-platform: org.hibernate.dialect.H2Dialect # db agnostic
# first create table then insert data:
    hibernate:
#      ddl-auto: validate # use once schema finalised
      ddl-auto: update # able to alter tables
    show-sql: true
# print sql queries in a readable format
    properties:
      hibernate:
        format_sql: true